# Generated by Django 2.1 on 2021-05-17 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compramaiz',
            name='idProductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Productor'),
        ),
        migrations.AlterField(
            model_name='documentocompra',
            name='idProductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Productor'),
        ),
        migrations.AlterField(
            model_name='facturatransporte',
            name='idResponsableTransporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.ResponsableTransporte'),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='idEmpresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Empresa'),
        ),
        migrations.AlterField(
            model_name='ventamaiz',
            name='idEmpresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Empresa'),
        ),
        migrations.AlterField(
            model_name='ventamaiz',
            name='idResponsableTransporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.ResponsableTransporte'),
        ),
    ]
