# Generated by Django 2.1 on 2021-05-17 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210517_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleingresoarticulos',
            name='idArticulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Articulo'),
        ),
        migrations.AlterField(
            model_name='detallesalidaarticulos',
            name='idArticulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Articulo'),
        ),
        migrations.AlterField(
            model_name='ingresoarticulo',
            name='idProveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Proveedor'),
        ),
        migrations.AlterField(
            model_name='salidaarticulo',
            name='idEmpleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Empleado'),
        ),
    ]
