# Generated by Django 2.1 on 2021-05-26 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210517_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='idProveedor',
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
    ]
