# Generated by Django 2.1 on 2021-05-28 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210526_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentocompra',
            name='tipoPago',
        ),
    ]
