# Generated by Django 2.1 on 2021-05-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_documentocompra_tipopago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción'),
        ),
    ]
